### PR TITLE
Fix `invalid type` deserialization error

### PR DESCRIPTION
**Pull request by aloucks**
Fix for the following error during deserialization:

    Error: Message("invalid type: string \"MY_FLAG\", expected a borrowed string", ...)

### CODE REVIEW

**Comment by H2CO3** [comment]
Hey, thanks for the contribution! I'll be able to have a look at this in a couple days (I'm busy right now). In the meantime, could you please how I can reproduce the problem?

**Comment by aloucks** [comment]
@H2CO3 Thanks! I added a unit test that fails on master but passes with these changes.

**Comment by H2CO3** [comment]
Hey there,

Thanks for the unit test, that's very useful. Unfortunately the fix seems to unconditionally allocate, given that `<Cow<T> as Deserialize<'_>>::deserialize()` [delegates](https://docs.serde.rs/src/serde/de/impls.rs.html#1727-1739) to `<T::Owned as Deserialize>::deserialize()`.

I'd like to avoid that unless it is completely necessary, so let me see if I can fix this without introducing an unconditional allocation.

**Comment by aloucks** [comment]
@H2CO3 I've updated this to prevent allocation for encoders that make use of `visit_borrowed_str`, such as `serde_json`.

**Comment by H2CO3** [comment]
Oh, that's very nice, thank you!

**Review by H2CO3 — APPROVED** [review]

**Comment by H2CO3** [comment]
@aloucks v0.1.3 released on crates.io.

**Pull request merged**
